# Generated by Django 4.1 on 2022-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='avaliacao',
            field=models.TextField(blank=True, max_length=510),
        ),
        migrations.AddField(
            model_name='curso',
            name='ementa',
            field=models.TextField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
