# Generated by Django 4.1 on 2022-08-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_curso_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='termos',
            field=models.BooleanField(default=True),
        ),
    ]
