# Generated by Django 4.1 on 2022-08-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_topico_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
